services:
  database:
    image: mysql:8.3
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: spocket
      MYSQL_ROOT_PASSWORD: spocket

  spocket:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./.env.compose:/app/.env.local

volumes:
  db_data:
