version: "3.1"

services:
  db:
    container_name: s-pocket-local-db
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PWD
      MYSQL_DATABASE: $DB_NAME

volumes:
  db_data:
