FROM mcr.microsoft.com/devcontainers/go:1.22

ENV TZ=Asia/Bangkok

# Install golangci-lint for linting
RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

CMD ["sleep", "infinity"]
